# -*- coding: utf-8 -*-
"""Real Estate and AirBnb Investment Trends

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q015wp3UWGhYI_iFYeejhWpPzLfhyuLb
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

sns.set(style="whitegrid")

# Airbnb datasets (semicolon-separated)
market = pd.read_csv("market_analysis.csv", sep=';', engine='python', on_bad_lines='skip')
amenities = pd.read_csv("amenities.csv", sep=';', engine='python', on_bad_lines='skip')
geo = pd.read_csv("geolocation.csv", sep=';', engine='python', on_bad_lines='skip')

# Real estate datasets (also semicolon-separated)
sales_92314 = pd.read_csv("sales_properties_total_zipcode_92314.csv", sep=';', engine='python', on_bad_lines='skip')
sales_92315 = pd.read_csv("sales_properties_total_zipcode_92315.csv", sep=';', engine='python', on_bad_lines='skip')
sales_92252 = pd.read_csv("sales_properties_total_zipcode_92252.csv", sep=';', engine='python', on_bad_lines='skip')
sales_92284 = pd.read_csv("sales_properties_total_zipcode_92284.csv", sep=';', engine='python', on_bad_lines='skip')
sales_pool_52 = pd.read_csv("sales_properties_with_pool_zipcode_92252.csv", sep=';', engine='python', on_bad_lines='skip')
sales_pool_84 = pd.read_csv("sales_properties_with_pool_zipcode_92284.csv", sep=';', engine='python', on_bad_lines='skip')

"""### Step 1 — Loading Airbnb & Real Estate Datasets
We load all datasets using `sep=';'` because every CSV in this project uses semicolon delimiters.  
We also enable `engine='python'` and `on_bad_lines='skip'` to safely handle malformed rows.

This ensures:
- All columns load correctly  
- No rows break the parser  
- The dataset is consistent and ready for cleaning  

This is the foundation for the entire analysis.
"""

def clean_columns(df):
    df.columns = [c.encode('ascii','ignore').decode('ascii').strip().lower() for c in df.columns]
    return df

market = clean_columns(market)
amenities = clean_columns(amenities)
geo = clean_columns(geo)

"""### Step 2 — Cleaning Column Names
We standardize column names by:
- removing BOM characters  
- stripping whitespace  
- converting to lowercase  

This prevents merge errors and ensures consistent column references throughout the notebook.

"""

print(market.columns)
print(amenities.columns)
print(geo.columns)

# Fix unified_id mismatch
market['unified_id'] = 'AIR' + market['unified_id'].astype(str).str.strip()
amenities['unified_id'] = amenities['unified_id'].astype(str).str.strip()
geo['unified_id'] = geo['unified_id'].astype(str).str.strip()

# Fix month mismatch
market['month'] = pd.to_datetime(market['month']).dt.strftime('%Y-%m')
amenities['month'] = pd.to_datetime(amenities['month']).dt.strftime('%Y-%m')

"""### Step 3 — Fixing Merge Keys (unified_id & month)
We ensure that `unified_id` and `month` match across all datasets.

Actions:
- Strip whitespace from IDs  
- Convert `month` to a consistent `YYYY-MM` format  

This step is critical because even tiny formatting differences will cause the merge to fail.  
After this fix, all datasets align correctly.

"""

df = pd.merge(
    market,
    amenities[['unified_id','month','pool','hot_tub']],
    on=['unified_id','month'],
    how='left'
)

df = pd.merge(
    df,
    geo[['unified_id','month','latitude','longitude']],
    on=['unified_id','month'],
    how='left'
)

df['pool'] = df['pool'].fillna(0).astype(int)
df['hot_tub'] = df['hot_tub'].fillna(0).astype(int)

"""### Step 4 — Merging Airbnb Market, Amenities, and Geolocation Data
We merge the three Airbnb datasets using `unified_id` and `month` as keys.

This creates a single, enriched dataset containing:
- performance metrics (revenue, occupancy, nightly rate)  
- amenity data (pool, hot tub)  
- geolocation data (latitude, longitude)  

We also fill missing amenity values with 0 to maintain binary consistency.

"""

df['pool'].value_counts()
df['hot_tub'].value_counts()

cols_to_fix = ['bedrooms','bathrooms','guests','revenue','occupancy','nightly rate']

for col in cols_to_fix:
    df[col] = df[col].astype(str).str.replace(r'[^0-9.]','',regex=True)
    df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0)

"""###  Step 5 — Cleaning Numeric Columns
Some numeric fields contain text (e.g., “15+ bedrooms”).  
We remove all non‑numeric characters and convert the columns to numeric types.

This ensures:
- accurate statistical analysis  
- correct plotting  
- valid correlation calculations  
"""

df['month_dt'] = pd.to_datetime(df['month'])

"""### Step 6 — Creating a Datetime Column
We convert the `month` string into a proper datetime object (`month_dt`).  
This allows us to:
- sort months chronologically  
- filter by year  
- create accurate time‑series visualizations  

"""

print(df.shape)
df.info()
df.describe()
df.isna().sum()

"""### Step 7 — Initial Exploratory Data Analysis
We inspect:
- dataset shape  
- column types  
- summary statistics  
- missing values  

This gives us a high‑level understanding of data quality and helps identify fields that need further cleaning.

"""

numeric_cols = ['revenue','occupancy','nightly rate']

plt.figure(figsize=(15,5))
for i, col in enumerate(numeric_cols,1):
    plt.subplot(1,3,i)
    sns.histplot(df[col], kde=True, bins=40)
    plt.title(f"{col} Distribution")
plt.tight_layout()
plt.show()

"""### Step 8 — Distribution Analysis
We visualize the distributions of revenue, occupancy, and nightly rate.

This helps us identify:
- skewness  
- outliers  
- typical value ranges  
- whether transformations might be needed  

These distributions form the foundation for later modeling and insights.

"""

plt.figure(figsize=(10,6))
sns.boxplot(data=df, x='city', y='revenue')
plt.title("Revenue Comparison: Big Bear vs Joshua Tree")
plt.show()

"""### Step 9 — Revenue Comparison Between Cities
We compare revenue distributions between Big Bear and Joshua Tree.

This reveals:
- which market earns more on average  
- how spread out the revenue is  
- whether one market is more volatile  

This is essential for investors comparing the two regions.

"""

plt.figure(figsize=(10,4))
sns.boxplot(data=df, x='pool', y='revenue')
plt.title("Revenue Impact of Pools")
plt.show()

plt.figure(figsize=(10,4))
sns.boxplot(data=df, x='hot_tub', y='occupancy')
plt.title("Occupancy Impact of Hot Tubs")
plt.show()

"""###  Step 10 — Visual Amenity Impact Analysis
We use boxplots to compare:
- revenue for listings with vs. without pools  
- occupancy for listings with vs. without hot tubs  

These visuals provide an immediate sense of whether amenities influence performance.

"""

numeric_cols = [
    'bedrooms', 'bathrooms', 'guests', 'revenue',
    'occupancy', 'nightly rate', 'pool', 'hot_tub'
]

plt.figure(figsize=(10,8))
sns.heatmap(df[numeric_cols].corr(), annot=True, cmap='coolwarm', center=0)
plt.title("Correlation Heatmap: Airbnb Market Data (Amenities Fixed)")
plt.show()

"""### Step 11 — Correlation Heatmap
We compute correlations between key numeric variables, including amenities.

This helps us understand:
- which features drive revenue  
- whether amenities correlate with performance  
- how occupancy and nightly rate relate  

This is a core component of the investment insights.

"""

df_filtered = df[(df['month_dt'].dt.year >= 2020) & (df['month_dt'].dt.year <= 2020)]

"""### Step 12 — Filtering Data to 2020–2021
Although amenities and geo datasets contain later years, the market data only covers 2020–2021.

We filter the dataset to avoid misleading trends and ensure all seasonality charts reflect complete data.

"""

plt.figure(figsize=(12,6))
sns.lineplot(
    data=df_filtered,
    x='month_dt',
    y='revenue',
    hue='city',
    estimator='mean'
)
plt.title("Average Monthly Revenue: Big Bear vs Joshua Tree (2020–2021)")
plt.ylabel("Average Revenue ($)")
plt.xlabel("Month")
plt.xticks(rotation=45)
plt.grid(True, alpha=0.3)
plt.show()

"""### Step 13 — Monthly Revenue Trend by City
We plot average monthly revenue for Big Bear and Joshua Tree.

This reveals:
- peak seasons  
- off‑season dips  
- differences in seasonal behavior between the two markets  

"""

plt.figure(figsize=(12,6))
sns.lineplot(
    data=df_filtered,
    x='month_dt',
    y='occupancy',
    hue='city',
    estimator='mean'
)
plt.title("Average Monthly Occupancy: Big Bear vs Joshua Tree")
plt.ylabel("Average Occupancy Rate")
plt.xlabel("Month")
plt.xticks(rotation=45)
plt.grid(True, alpha=0.3)
plt.show()

"""### Step 14 — Monthly Occupancy Trend by City
We visualize occupancy seasonality for each city.

This helps explain revenue patterns and highlights demand cycles.

"""

df_monthly = df_filtered.groupby('month_dt')['revenue'].mean().reset_index()

plt.figure(figsize=(12,6))
sns.lineplot(data=df_monthly, x='month_dt', y='revenue')
plt.title("Overall Monthly Revenue Trend")
plt.ylabel("Average Revenue ($)")
plt.xlabel("Month")
plt.xticks(rotation=45)
plt.grid(True, alpha=0.3)
plt.show()

"""### Step 15 — Overall Revenue Seasonality
We compute the average revenue across all listings for each month.

This provides a clean, high‑level view of market‑wide seasonality.

"""

df_monthly_occ = df_filtered.groupby('month_dt')['occupancy'].mean().reset_index()

plt.figure(figsize=(12,6))
sns.lineplot(data=df_monthly_occ, x='month_dt', y='occupancy')
plt.title("Overall Monthly Occupancy Trend")
plt.ylabel("Average Occupancy Rate")
plt.xlabel("Month")
plt.xticks(rotation=45)
plt.grid(True, alpha=0.3)
plt.show()

"""### Step 16 — Overall Occupancy Seasonality
We compute the average occupancy rate per month across all listings.

This helps identify:
- high‑demand periods  
- low‑demand periods  
- potential pricing optimization windows  

"""

df.groupby('pool')['revenue'].mean()

df.groupby('hot_tub')['occupancy'].mean()

plt.figure(figsize=(10,4))
sns.boxplot(data=df_filtered, x='pool', y='revenue')
plt.title("Revenue Impact of Pools")
plt.show()

plt.figure(figsize=(10,4))
sns.boxplot(data=df, x='hot_tub', y='occupancy')
plt.title("Occupancy Impact of Hot Tubs")
plt.show()

"""###  Step 17 — Revenue Difference for Pool vs. No Pool
We calculate the average revenue for listings with and without pools.

This quantifies the revenue uplift associated with having a pool.
###  Step 18 — Occupancy Difference for Hot Tub vs. No Hot Tub
We compute the average occupancy for listings with and without hot tubs.

This measures how much hot tubs influence booking demand.

"""

from scipy.stats import ttest_ind

# Pool revenue test
rev_pool = df[df['pool']==1]['revenue']
rev_no_pool = df[df['pool']==0]['revenue']
t_pool = ttest_ind(rev_pool, rev_no_pool, equal_var=False)

# Hot tub occupancy test
occ_hot = df[df['hot_tub']==1]['occupancy']
occ_no_hot = df[df['hot_tub']==0]['occupancy']
t_hot = ttest_ind(occ_hot, occ_no_hot, equal_var=False)

t_pool, t_hot

"""###  Step 19 — Statistical Significance Testing (t‑tests)
We run two independent t‑tests:

1. **Revenue:** Pool vs. No Pool  
2. **Occupancy:** Hot Tub vs. No Hot Tub  

This determines whether the observed differences are statistically significant  
or could have occurred by random chance.

This step elevates the analysis from descriptive to inferential statistics.

##Project Summary(....finallyyy)
1. This project analyzes short‑term rental performance across Big Bear and Joshua Tree using Airbnb market data, amenity data, and geolocation data. The goal was to understand how property characteristics, amenities, and seasonality influence revenue and occupancy and to identify which factors drive the highest
return on investment (ROI) for hosts and real estate investors.

2. The analysis begins by loading and cleaning multiple datasets, all of which required robust parsing due to inconsistent delimiters and malformed rows. After standardizing column names and fixing key mismatches in unified_id and month, the datasets were merged into a single, enriched Airbnb performance table containing revenue, occupancy, amenities, and location information.

3. Initial exploratory data analysis (EDA) examined distributions, missing values, and correlations across key variables. Seasonality analysis revealed distinct demand cycles for Big Bear and Joshua Tree, with Big Bear peaking in winter (ski season) and Joshua Tree peaking in spring and fall (hiking season). These patterns were visualized through monthly revenue and occupancy trends filtered to the years 2020–2021, ensuring alignment with the available market data.

4. Amenity ROI analysis quantified the impact of pools and hot tubs on listing performance. Listings with pools showed higher average revenue, while listings with hot tubs demonstrated higher occupancy rates. Independent t‑tests confirmed that these differences were statistically significant, indicating that amenities meaningfully influence booking behavior and earning potential.

Overall, this project provides a data‑driven framework for evaluating short‑term rental investments, highlighting how seasonality, amenities, and property characteristics shape financial outcomes. The insights can support pricing strategies, renovation decisions, and market selection for investors seeking to maximize Airbnb profitability.
"""